
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Falcon.MtG
{

using System;
    using System.Collections.Generic;
    
public partial class Card
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Card()
    {

        this.IsPrimarySide = true;

        this.Sets = new HashSet<Set>();

        this.Colors = new HashSet<Color>();

        this.ColorIdentity = new HashSet<Color>();

        this.Supertypes = new HashSet<Supertype>();

        this.Types = new HashSet<Type>();

        this.Subtypes = new HashSet<Subtype>();

        this.Abilities = new HashSet<Ability>();

        this.Rarities = new HashSet<Rarity>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<int> MultiverseId { get; set; }

    public string ManaCost { get; set; }

    public Nullable<int> CMC { get; set; }

    public string TypeLine { get; set; }

    public string OracleText { get; set; }

    public string FlavorText { get; set; }

    public Nullable<int> Power { get; set; }

    public Nullable<int> Toughness { get; set; }

    public bool CommanderLegal { get; set; }

    public System.DateTime LatestPrintDate { get; set; }

    public bool IsPrimarySide { get; set; }

    public bool TinyLeadersLegal { get; set; }

    public bool BrawlLegal { get; set; }

    public bool TinyLeadersCmdrLegal { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Set> Sets { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Color> Colors { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Color> ColorIdentity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Supertype> Supertypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Type> Types { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Subtype> Subtypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ability> Abilities { get; set; }

    public virtual Card OtherSide { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rarity> Rarities { get; set; }

}

}
