
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Falcon.MtG
{

using System;
    using System.Collections.Generic;
    
public partial class Card
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Card()
    {

        this.Colors = new HashSet<Color>();

        this.ColorIdentity = new HashSet<Color>();

        this.Supertypes = new HashSet<Supertype>();

        this.Types = new HashSet<CardType>();

        this.Subtypes = new HashSet<Subtype>();

        this.Printings = new HashSet<Printing>();

        this.Keywords = new HashSet<Keyword>();

        this.OtherSides = new HashSet<Card>();

        this.Legalities = new HashSet<Legality>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public string ManaCost { get; set; }

    public double CMC { get; set; }

    public string TypeLine { get; set; }

    public string OracleText { get; set; }

    public string Power { get; set; }

    public string Toughness { get; set; }

    public string Loyalty { get; set; }

    public int LayoutID { get; set; }

    public Nullable<int> MainSideID { get; set; }

    public string Side { get; set; }

    public Nullable<int> EDHRECRank { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Color> Colors { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Color> ColorIdentity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Supertype> Supertypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CardType> Types { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Subtype> Subtypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Printing> Printings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Keyword> Keywords { get; set; }

    public virtual Layout Layout { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Card> OtherSides { get; set; }

    public virtual Card MainSide { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Legality> Legalities { get; set; }

}

}
