
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Falcon.MtG
{

using System;
    using System.Collections.Generic;
    
public partial class ExceptionLog
{

    public int ID { get; set; }

    public string RequestJson { get; set; }

    public string Outcome { get; set; }

    public string Exception { get; set; }

}

}
