
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Falcon.MtG
{

using System;
    using System.Collections.Generic;
    
public partial class Legality
{

    public int ID { get; set; }

    public string Format { get; set; }

    public bool LegalAsCommander { get; set; }

    public bool Legal { get; set; }

    public int CardID { get; set; }



    public virtual Card Card { get; set; }

}

}
