

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Falcon.MtG
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MTGDBContainer : DbContext
{
    public MTGDBContainer()
        : base("name=MTGDBContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Card> Cards { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<Supertype> Supertypes { get; set; }

    public virtual DbSet<Subtype> Subtypes { get; set; }

    public virtual DbSet<CardType> CardTypes { get; set; }

    public virtual DbSet<Set> Sets { get; set; }

    public virtual DbSet<Keyword> Keywords { get; set; }

    public virtual DbSet<Legality> Legalities { get; set; }

    public virtual DbSet<Printing> Printings { get; set; }

    public virtual DbSet<Rarity> Rarities { get; set; }

    public virtual DbSet<ExceptionLog> ExceptionLogEntries { get; set; }

    public virtual DbSet<Layout> Layouts { get; set; }

    public virtual DbSet<Artist> Artists { get; set; }

    public virtual DbSet<Watermark> Watermarks { get; set; }

    public virtual DbSet<Frame> Frames { get; set; }

    public virtual DbSet<Border> Borders { get; set; }

    public virtual DbSet<SetType> SetTypes { get; set; }

    public virtual DbSet<Pricing> Pricings { get; set; }

    public virtual DbSet<Block> Blocks { get; set; }

}

}

