
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Falcon.MtG
{

using System;
    using System.Collections.Generic;
    
public partial class Printing
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Printing()
    {

        this.Pricings = new HashSet<Pricing>();

    }


    public int ID { get; set; }

    public int MultiverseId { get; set; }

    public string FlavorText { get; set; }

    public string CollectorNumber { get; set; }

    public string Side { get; set; }

    public Nullable<int> ArtistID { get; set; }

    public Nullable<int> WatermarkID { get; set; }

    public int FrameID { get; set; }

    public int RarityID { get; set; }

    public int BorderID { get; set; }

    public int SetID { get; set; }

    public int CardID { get; set; }



    public virtual Artist Artist { get; set; }

    public virtual Watermark Watermark { get; set; }

    public virtual Frame Frame { get; set; }

    public virtual Rarity Rarity { get; set; }

    public virtual Border Border { get; set; }

    public virtual Set Set { get; set; }

    public virtual Card Card { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pricing> Pricings { get; set; }

}

}
