
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Falcon.MtG
{

using System;
    using System.Collections.Generic;
    
public partial class Set
{

    public int ID { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public System.DateTime Date { get; set; }

    public string Block { get; set; }

    public string Type { get; set; }

    public string Border { get; set; }

}

}
